from collections.abc import Callable, Iterable, Sequence
from typing import Any, Literal

from typing_extensions import Self

_Align = Literal["l", "c", "r"]
_VAlign = Literal["t", "m", "b"]
_DType = Literal["a", "t", "f", "e", "i", "b"] | Callable[[Any], str]

class ArraySizeError(Exception):
    msg: str
    def __init__(self, msg: str) -> None: ...

class FallbackToText(Exception): ...

def obj2unicode(obj: object) -> str: ...

class Texttable:
    BORDER: int
    HEADER: int
    HLINES: int
    VLINES: int
    def __init__(self, max_width: int = 80) -> None: ...
    def reset(self) -> Self: ...
    def set_max_width(self, max_width: int) -> Self: ...
    def set_chars(self, array: Sequence[str]) -> Self: ...
    def set_deco(self, deco: int) -> Self: ...
    def set_header_align(self, array: Sequence[_Align]) -> Self: ...
    def set_cols_align(self, array: Sequence[_Align]) -> Self: ...
    def set_cols_valign(self, array: Sequence[_VAlign]) -> Self: ...
    def set_cols_dtype(self, array: Sequence[_DType]) -> Self: ...
    def set_cols_width(self, array: Sequence[int]) -> Self: ...
    def set_precision(self, width: int) -> Self: ...
    def header(self, array: Sequence[Any]) -> Self: ...
    def add_row(self, array: Sequence[Any]) -> Self: ...
    def add_rows(self, rows: Sequence[Sequence[Any]] | Iterable[Sequence[Any]], header: bool = True) -> Self: ...
    # Actually returns None if there is no header and no rows, but typed as
    # str so callers that always add rows don't need to handle it
    def draw(self) -> str: ...
